// Generated by `npm run typegen` in travel-mate-cms/studio from the enabled language documents.
// Don't edit by hand: enable a language in the Studio and run typegen again
export const LANGUAGES = [
  { id: "da", title: "Dansk" },
  { id: "en", title: "English" },
  { id: "es", title: "Español" },
] as const;

export type Language = (typeof LANGUAGES)[number]["id"];
